FROM node:17.6-alpine3.14 as BUILDER
EXPOSE 3000
WORKDIR /app
ENV NODE_ENV=${NODE_ENV}
COPY ./package.json ./yarn.lock* ./package-lock.json* ./
RUN yarn install
COPY . .

FROM node:17.6-alpine3.14
WORKDIR /app
COPY --from=BUILDER /app ./
CMD ["yarn","dev"]